/*
 * Sample property records for the properties table. Each object conforms
 * to the `Property` interface defined in `src/types/property.ts`. In a
 * production environment, you would replace this with data fetched
 * from your API via a store or custom hook.
 */

import type { Property } from '@/types/property'

export const properties: Property[] = [
  {
    id: 'p1',
    name: 'Nyari Heights',
    propertyType: 'Residential',
    unitsCount: 24,
    isActive: true,
    country: 'Kenya',
    city: 'Nairobi',
    addressLine1: 'Nyari Rd',
    addressLine2: 'Near New Muthaiga',
    description: 'Luxury apartments overlooking the city',
    latitude: -1.243,
    longitude: 36.789,
    ownerName: 'James Mwangi',
    ownerEmail: 'jmwangi@example.com',
    ownerPhone: '+254712345678',
    amenities: ['Pool', 'Gym'],
    images: undefined,
    createdAt: '2025-02-01T09:00:00Z',
    updatedAt: '2025-02-01T09:00:00Z',
  },
  {
    id: 'p2',
    name: 'City Mall Plaza',
    propertyType: 'Commercial',
    unitsCount: 10,
    isActive: true,
    country: 'Kenya',
    city: 'Mombasa',
    addressLine1: 'Links Rd',
    addressLine2: null,
    description: 'Retail space in the heart of Nyali',
    latitude: -4.043,
    longitude: 39.668,
    ownerName: 'Ali Karim',
    ownerEmail: 'akarim@example.com',
    ownerPhone: '+254701234567',
    amenities: ['Parking'],
    images: undefined,
    createdAt: '2025-03-12T13:30:00Z',
    updatedAt: '2025-03-12T13:30:00Z',
  },
  {
    id: 'p3',
    name: 'Thika Business Park',
    propertyType: 'MixedUse',
    unitsCount: 15,
    isActive: false,
    country: 'Kenya',
    city: 'Thika',
    addressLine1: 'Garissa Rd',
    addressLine2: null,
    description: 'Office and retail complex',
    latitude: -1.041,
    longitude: 37.070,
    ownerName: 'Galaxy Investments',
    ownerEmail: 'info@galaxy.com',
    ownerPhone: '+254722345678',
    amenities: ['Cafeteria', 'Parking'],
    images: undefined,
    createdAt: '2025-01-25T10:00:00Z',
    updatedAt: '2025-01-25T10:00:00Z',
  },
  {
    id: 'p4',
    name: 'Riverside Industrial Park',
    propertyType: 'Commercial',
    unitsCount: 8,
    isActive: true,
    country: 'Kenya',
    city: 'Nairobi',
    addressLine1: 'Riverside Dr',
    addressLine2: null,
    description: 'Warehousing and light industry',
    latitude: -1.281,
    longitude: 36.815,
    ownerName: 'Acme Corp',
    ownerEmail: 'contact@acme.com',
    ownerPhone: '+254733456789',
    amenities: ['Security'],
    images: undefined,
    createdAt: '2025-04-10T12:15:00Z',
    updatedAt: '2025-04-10T12:15:00Z',
  },
  {
    id: 'p5',
    name: 'Savannah Residences',
    propertyType: 'Residential',
    unitsCount: 30,
    isActive: true,
    country: 'Kenya',
    city: 'Machakos',
    addressLine1: 'Mombasa Rd',
    addressLine2: null,
    description: 'Gated community with landscaped gardens',
    latitude: -1.402,
    longitude: 37.014,
    ownerName: 'Savannah Holdings',
    ownerEmail: 'sales@savannah.com',
    ownerPhone: '+254799123456',
    amenities: ['Pool', 'Clubhouse'],
    images: undefined,
    createdAt: '2025-05-20T15:45:00Z',
    updatedAt: '2025-05-20T15:45:00Z',
  },
]

export default properties