import type { BalanceRow } from './types'

export const mockBalances: BalanceRow[] = [
  {
    id: 'bal_001',
    kind: 'AR',
    entityName: 'Brian Otieno',
    unit: 'Apt 1A',
    propertyName: 'Sunset Heights',
    currency: 'KES',
    openingBalance: 0,
    totalDebits: 40000, // charges (rent)
    totalCredits: 30000, // payments
    balance: 10000, // positive => customer owes (A/R)
    dueDate: new Date('2025-08-05'),
    ledger: [
      {
        id: 'l1',
        date: new Date('2025-08-01'),
        reference: 'INV-1001',
        description: 'August Rent',
        debit: 40000,
        credit: 0,
        currency: 'KES',
      },
      {
        id: 'l2',
        date: new Date('2025-08-08'),
        reference: 'MPESA-QW34N9',
        description: 'Payment',
        debit: 0,
        credit: 30000,
        currency: 'KES',
      },
    ],
  },
  {
    id: 'bal_002',
    kind: 'AR',
    entityName: 'Fatuma Ali',
    unit: 'Apt 2A',
    propertyName: 'Sunset Heights',
    currency: 'KES',
    openingBalance: 5000,
    totalDebits: 41000,
    totalCredits: 20000,
    balance: 26000,
    dueDate: new Date('2025-08-05'),
    ledger: [
      {
        id: 'l3',
        date: new Date('2025-07-31'),
        reference: 'BAL-FWD',
        description: 'B/F',
        debit: 5000,
        credit: 0,
        currency: 'KES',
      },
      {
        id: 'l4',
        date: new Date('2025-08-01'),
        reference: 'INV-1002',
        description: 'August Rent',
        debit: 41000,
        credit: 0,
        currency: 'KES',
      },
      {
        id: 'l5',
        date: new Date('2025-08-12'),
        reference: 'CARD-8HJ2D4',
        description: 'Payment',
        debit: 0,
        credit: 20000,
        currency: 'KES',
      },
    ],
  },
  {
    id: 'bal_003',
    kind: 'AR',
    entityName: 'TechHive Africa',
    unit: 'Office 501',
    propertyName: 'Westlands Tower',
    currency: 'KES',
    openingBalance: 0,
    totalDebits: 100000,
    totalCredits: 100000,
    balance: 0,
    dueDate: new Date('2025-08-01'),
    ledger: [
      {
        id: 'l6',
        date: new Date('2025-08-01'),
        reference: 'INV-2001',
        description: 'Office Lease',
        debit: 100000,
        credit: 0,
        currency: 'KES',
      },
      {
        id: 'l7',
        date: new Date('2025-08-01'),
        reference: 'BANK-TRX-9931',
        description: 'Payment',
        debit: 0,
        credit: 100000,
        currency: 'KES',
      },
    ],
  },
  {
    id: 'bal_004',
    kind: 'AP',
    entityName: 'Global Logistics Ltd.',
    unit: 'Warehouse 1',
    propertyName: 'Industrial Trade Park',
    currency: 'KES',
    openingBalance: 0,
    totalDebits: 0,
    totalCredits: 350000,
    balance: -350000, // negative => we owe vendor (A/P)
    dueDate: new Date('2025-08-10'),
    ledger: [
      {
        id: 'l8',
        date: new Date('2025-08-03'),
        reference: 'DEP-REF',
        description: 'Deposit Refund',
        debit: 0,
        credit: 350000,
        currency: 'KES',
      },
    ],
  },
].map((r) => ({ ...r, aging: r.aging ?? {} }))
