import type { Property } from './types'

export const properties: Property[] = [
  {
    id: 'prop_sh',
    name: 'Sunset Heights',
    address: 'Ngong Road, Nairobi',
    imageUrl:
      'https://images.unsplash.com/photo-1464983953574-0892a716854b?q=80&w=400',
    ownerId: 'owner1',
    propertyType: 'Residential',
    mrRequestCounts: { open: 2, inProgress: 1 },
    units: [
      {
        id: 'unit_sh_1a',
        unitIdentifier: 'Apt 1A',
        status: 'Occupied',
        leaseType: 'Residential Rent',
        squareFootage: 800,
        currentLeaseAmount: 40000,
        currency: 'KES',
        tenantName: 'Brian Otieno',
        leaseEndDate: new Date('2026-06-30'),
      },
      {
        id: 'unit_sh_1b',
        unitIdentifier: 'Apt 1B',
        status: 'Vacant',
        leaseType: 'Residential Rent',
        squareFootage: 850,
        currentLeaseAmount: 42000,
        currency: 'KES',
      },
      {
        id: 'unit_sh_2a',
        unitIdentifier: 'Apt 2A',
        status: 'Occupied',
        leaseType: 'Residential Rent',
        squareFootage: 820,
        currentLeaseAmount: 41000,
        currency: 'KES',
        tenantName: 'Fatuma Ali',
        leaseEndDate: new Date('2025-12-31'),
      },
      {
        id: 'unit_sh_2b',
        unitIdentifier: 'Apt 2B',
        status: 'Under Maintenance',
        leaseType: 'Residential Rent',
        squareFootage: 850,
        currentLeaseAmount: 42000,
        currency: 'KES',
      },
    ],
    mrRequests: [
      {
        id: 'mr_prop_sh_001',
        title: 'Leaking tap in kitchen',
        status: 'Open',
        priority: 'Medium',
        unitIdentifier: 'Apt 1A',
        createdAt: new Date('2025-08-08'),
      },
      {
        id: 'mr_prop_sh_002',
        title: 'Power socket replacement',
        status: 'In Progress',
        priority: 'High',
        unitIdentifier: 'Apt 2A',
        createdAt: new Date('2025-08-05'),
      },
      {
        id: 'mr_prop_sh_003',
        title: 'Corridor light not working',
        status: 'Open',
        priority: 'Low',
        unitIdentifier: 'Apt 1B',
        createdAt: new Date('2025-08-10'),
      },
    ],
  },
  {
    id: 'prop_nyali',
    name: 'Nyali Executive Residences',
    address: 'Links Road, Nyali, Mombasa',
    imageUrl:
      'https://images.unsplash.com/photo-1494526585095-c41746248156?q=80&w=400',
    ownerId: 'owner2',
    propertyType: 'Residential',
    mrRequestCounts: { open: 0, inProgress: 0 },
    units: [
      {
        id: 'unit_nyali_main',
        unitIdentifier: 'Main Villa',
        status: 'Vacant',
        leaseType: 'Residential Rent',
        squareFootage: 3500,
        currentLeaseAmount: 120000,
        currency: 'KES',
      },
    ],
    mrRequests: [],
  },
  {
    id: 'prop_kbh',
    name: 'Karen Business Hub',
    address: 'Karen Road, Nairobi',
    imageUrl:
      'https://images.unsplash.com/photo-1543269664-7e9792d3ba1a?q=80&w=400',
    ownerId: 'owner3',
    propertyType: 'Commercial',
    mrRequestCounts: { open: 5, inProgress: 3 },
    units: [
      {
        id: 'unit_kbh_201',
        unitIdentifier: 'Suite 201',
        status: 'Occupied',
        leaseType: 'Commercial Lease',
        squareFootage: 1200,
        currentLeaseAmount: 150000,
        currency: 'KES',
        tenantName: 'Innovate Solutions Ltd.',
        leaseEndDate: new Date('2028-08-31'),
      },
      {
        id: 'unit_kbh_202',
        unitIdentifier: 'Suite 202',
        status: 'Vacant',
        leaseType: 'Commercial Lease',
        squareFootage: 1350,
        currentLeaseAmount: 165000,
        currency: 'KES',
      },
      {
        id: 'unit_kbh_300',
        unitIdentifier: 'Rooftop Cafe',
        status: 'Occupied',
        leaseType: 'Commercial Lease',
        squareFootage: 2000,
        currentLeaseAmount: 250000,
        currency: 'KES',
        tenantName: 'The Grind Cafe',
        leaseEndDate: new Date('2030-01-31'),
      },
    ],
    mrRequests: [
      {
        id: 'mr_prop_kbh_001',
        title: 'AC not cooling (Boardroom)',
        status: 'Open',
        priority: 'High',
        unitIdentifier: 'Suite 201',
        createdAt: new Date('2025-08-09'),
      },
      {
        id: 'mr_prop_kbh_002',
        title: 'Network cabling check',
        status: 'Open',
        priority: 'Medium',
        unitIdentifier: 'Suite 201',
        createdAt: new Date('2025-08-06'),
      },
      {
        id: 'mr_prop_kbh_003',
        title: 'Water pressure low in restrooms',
        status: 'In Progress',
        priority: 'High',
        unitIdentifier: 'Suite 202',
        createdAt: new Date('2025-08-07'),
      },
      {
        id: 'mr_prop_kbh_004',
        title: 'Elevator periodic service',
        status: 'In Progress',
        priority: 'Medium',
        createdAt: new Date('2025-08-01'),
      },
      {
        id: 'mr_prop_kbh_005',
        title: 'Emergency exit signage replacement',
        status: 'Open',
        priority: 'Low',
        createdAt: new Date('2025-08-03'),
      },
      {
        id: 'mr_prop_kbh_006',
        title: 'Kitchen hood deep-clean',
        status: 'Open',
        priority: 'Medium',
        unitIdentifier: 'Rooftop Cafe',
        createdAt: new Date('2025-08-02'),
      },
      {
        id: 'mr_prop_kbh_007',
        title: 'Parking gate sensor fault',
        status: 'In Progress',
        priority: 'High',
        createdAt: new Date('2025-08-04'),
      },
      {
        id: 'mr_prop_kbh_008',
        title: 'Exterior facade touch-up',
        status: 'Open',
        priority: 'Low',
        createdAt: new Date('2025-08-10'),
      },
    ],
  },
  {
    id: 'prop_gpv',
    name: 'Greenpark Villas',
    address: 'Greenpark Estate, Athi River',
    imageUrl:
      'https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=400',
    ownerId: 'owner1',
    propertyType: 'Residential',
    mrRequestCounts: { open: 0, inProgress: 1 },
    units: [
      {
        id: 'unit_gpv_main',
        unitIdentifier: 'Main House',
        status: 'Occupied',
        leaseType: 'Residential Rent',
        squareFootage: 2800,
        currentLeaseAmount: 65000,
        currency: 'KES',
        tenantName: 'Mwikali Ndunda',
        leaseEndDate: new Date('2025-11-30'),
      },
    ],
    mrRequests: [
      {
        id: 'mr_prop_gpv_001',
        title: 'Solar heater inspection',
        status: 'In Progress',
        priority: 'Medium',
        unitIdentifier: 'Main House',
        createdAt: new Date('2025-08-11'),
      },
    ],
  },
  {
    id: 'prop_wt',
    name: 'Westlands Tower',
    address: 'Woodvale Grove, Westlands, Nairobi',
    imageUrl:
      'https://images.unsplash.com/photo-1501183638710-841dd1904471?q=80&w=400',
    ownerId: 'owner4',
    propertyType: 'Mixed-Use',
    mrRequestCounts: { open: 1, inProgress: 2 },
    units: [
      {
        id: 'unit_wt_501',
        unitIdentifier: 'Office 501',
        status: 'Occupied',
        leaseType: 'Commercial Lease',
        squareFootage: 900,
        currentLeaseAmount: 100000,
        currency: 'KES',
        tenantName: 'TechHive Africa',
        leaseEndDate: new Date('2027-04-15'),
      },
      {
        id: 'unit_wt_10a',
        unitIdentifier: 'Apartment 10A',
        status: 'Vacant',
        leaseType: 'Residential Rent',
        squareFootage: 1100,
        currentLeaseAmount: 80000,
        currency: 'KES',
      },
    ],
    mrRequests: [
      {
        id: 'mr_prop_wt_001',
        title: 'Lift stops intermittently at Floor 3',
        status: 'In Progress',
        priority: 'High',
        createdAt: new Date('2025-08-08'),
      },
      {
        id: 'mr_prop_wt_002',
        title: 'Painting scuffs in lobby',
        status: 'Open',
        priority: 'Low',
        createdAt: new Date('2025-08-12'),
      },
      {
        id: 'mr_prop_wt_003',
        title: 'Office 501 AC filter replacement',
        status: 'In Progress',
        priority: 'Medium',
        unitIdentifier: 'Office 501',
        createdAt: new Date('2025-08-05'),
      },
    ],
  },
  {
    id: 'prop_itp',
    name: 'Industrial Trade Park',
    address: 'Eastern Bypass, Nairobi',
    imageUrl:
      'https://images.unsplash.com/photo-1581090465140-5c41de5a0d0f?q=80&w=400',
    ownerId: 'owner5',
    propertyType: 'Industrial',
    mrRequestCounts: { open: 0, inProgress: 0 },
    units: [
      {
        id: 'unit_itp_1',
        unitIdentifier: 'Warehouse 1',
        status: 'Occupied',
        leaseType: 'Commercial Lease',
        squareFootage: 5000,
        currentLeaseAmount: 350000,
        currency: 'KES',
        tenantName: 'Global Logistics Ltd.',
        leaseEndDate: new Date('2031-10-01'),
      },
      {
        id: 'unit_itp_2',
        unitIdentifier: 'Warehouse 2',
        status: 'Vacant',
        leaseType: 'Commercial Lease',
        squareFootage: 5200,
        currentLeaseAmount: 360000,
        currency: 'KES',
      },
    ],
    mrRequests: [],
  },

  // --- New Additional Properties ---
  {
    id: 'prop_galleria',
    name: 'Galleria Mall',
    address: 'Langata Road, Nairobi',
    imageUrl:
      'https://images.unsplash.com/photo-1582582494700-7e4d85f0d863?q=80&w=400',
    ownerId: 'owner6',
    propertyType: 'Commercial',
    mrRequestCounts: { open: 2, inProgress: 1 },
    units: [
      {
        id: 'unit_galleria_1',
        unitIdentifier: 'Shop G1',
        status: 'Occupied',
        leaseType: 'Commercial Lease',
        squareFootage: 1200,
        currentLeaseAmount: 200000,
        currency: 'KES',
        tenantName: 'Java House',
        leaseEndDate: new Date('2029-09-01'),
      },
      {
        id: 'unit_galleria_2',
        unitIdentifier: 'Shop G2',
        status: 'Vacant',
        leaseType: 'Commercial Lease',
        squareFootage: 900,
        currentLeaseAmount: 150000,
        currency: 'KES',
      },
    ],
    mrRequests: [
      {
        id: 'mr_prop_galleria_001',
        title: 'Escalator step noise',
        status: 'Open',
        priority: 'Medium',
        createdAt: new Date('2025-08-09'),
      },
      {
        id: 'mr_prop_galleria_002',
        title: 'Roof leak near atrium',
        status: 'In Progress',
        priority: 'High',
        createdAt: new Date('2025-08-06'),
      },
      {
        id: 'mr_prop_galleria_003',
        title: 'Shop G2 rolling shutter service',
        status: 'Open',
        priority: 'Low',
        unitIdentifier: 'Shop G2',
        createdAt: new Date('2025-08-12'),
      },
    ],
  },
  {
    id: 'prop_diani_resort',
    name: 'Diani Beach Resort',
    address: 'Diani Beach Road, Kwale',
    imageUrl:
      'https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?q=80&w=400',
    ownerId: 'owner7',
    propertyType: 'Mixed-Use',
    mrRequestCounts: { open: 0, inProgress: 0 },
    units: [
      {
        id: 'unit_diani_villa1',
        unitIdentifier: 'Villa 1',
        status: 'Occupied',
        leaseType: 'Residential Rent',
        squareFootage: 3200,
        currentLeaseAmount: 3000,
        currency: 'USD',
        tenantName: 'Diplomatic Family',
        leaseEndDate: new Date('2027-12-15'),
      },
      {
        id: 'unit_diani_restaurant',
        unitIdentifier: 'Seafront Restaurant',
        status: 'Vacant',
        leaseType: 'Commercial Lease',
        squareFootage: 1500,
        currentLeaseAmount: 2500,
        currency: 'USD',
      },
    ],
    mrRequests: [],
  },
  {
    id: 'prop_kilimani_serviced',
    name: 'Kilimani Serviced Suites',
    address: 'Lenana Road, Nairobi',
    imageUrl:
      'https://images.unsplash.com/photo-1586105251261-72a756497a12?q=80&w=400',
    ownerId: 'owner8',
    propertyType: 'Residential',
    mrRequestCounts: { open: 3, inProgress: 1 },
    units: [
      {
        id: 'unit_kss_701',
        unitIdentifier: 'Penthouse 701',
        status: 'Occupied',
        leaseType: 'Residential Rent',
        squareFootage: 2000,
        currentLeaseAmount: 2500,
        currency: 'USD',
        tenantName: 'UN Staff',
        leaseEndDate: new Date('2026-03-01'),
      },
      {
        id: 'unit_kss_302',
        unitIdentifier: 'Suite 302',
        status: 'Vacant',
        leaseType: 'Residential Rent',
        squareFootage: 1000,
        currentLeaseAmount: 1500,
        currency: 'USD',
      },
    ],
    mrRequests: [
      {
        id: 'mr_prop_kss_001',
        title: 'Penthouse 701 jacuzzi pump issue',
        status: 'Open',
        priority: 'High',
        unitIdentifier: 'Penthouse 701',
        createdAt: new Date('2025-08-10'),
      },
      {
        id: 'mr_prop_kss_002',
        title: 'Corridor carpet replacement (Level 7)',
        status: 'Open',
        priority: 'Low',
        createdAt: new Date('2025-08-03'),
      },
      {
        id: 'mr_prop_kss_003',
        title: 'Smoke detector false alarms',
        status: 'In Progress',
        priority: 'Medium',
        createdAt: new Date('2025-08-07'),
      },
      {
        id: 'mr_prop_kss_004',
        title: 'Suite 302 shower door alignment',
        status: 'Open',
        priority: 'Low',
        unitIdentifier: 'Suite 302',
        createdAt: new Date('2025-08-12'),
      },
    ],
  },
]
