import type { Payment } from './types'

export const mockPayments: Payment[] = [
  {
    id: 'pay_001',
    reference: 'MPESA-QW34N9',
    tenantName: 'Brian Otieno',
    unit: 'Apt 1A',
    propertyName: 'Sunset Heights',
    method: 'Mpesa',
    amount: 40000,
    currency: 'KES',
    status: 'Completed',
    direction: 'Incoming',
    createdAt: new Date('2025-08-08T10:20:00'),
    notes: 'August rent',
    invoiceId: 'inv_1001',
  },
  {
    id: 'pay_002',
    reference: 'CARD-8HJ2D4',
    tenantName: 'Fatuma Ali',
    unit: 'Apt 2A',
    propertyName: 'Sunset Heights',
    method: 'Card',
    amount: 41000,
    currency: 'KES',
    status: 'Pending',
    direction: 'Incoming',
    createdAt: new Date('2025-08-12T08:55:00'),
  },
  {
    id: 'pay_003',
    reference: 'BANK-TRX-9931',
    tenantName: 'TechHive Africa',
    unit: 'Office 501',
    propertyName: 'Westlands Tower',
    method: 'Bank',
    amount: 100000,
    currency: 'KES',
    status: 'Completed',
    direction: 'Incoming',
    createdAt: new Date('2025-08-01T12:15:00'),
  },
  {
    id: 'pay_004',
    reference: 'CASH-44321',
    tenantName: 'Global Logistics Ltd.',
    unit: 'Warehouse 1',
    propertyName: 'Industrial Trade Park',
    method: 'Cash',
    amount: 350000,
    currency: 'KES',
    status: 'Refunded',
    direction: 'Outgoing',
    createdAt: new Date('2025-08-03T16:00:00'),
    notes: 'Deposit refund',
  },
]
